[workspace]
members = ["python"]

[package]
name = "super_simple_mesh_viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
smooth-bevy-cameras = "0.8.0"
ndarray = "0.15.6"
